import os
import requests

SEVERITY_EMOJI = {"high": "🔴", "medium": "🟡", "low": "🟢"}

def _format_findings(findings: list, category_name: str) -> str:
    if not findings:
        return ""
    lines = [f"\n### {category_name}\n"]
    for item in findings:
        sev = item.get("severity", "low")
        emoji = SEVERITY_EMOJI.get(sev, "⚪")
        file_ref = f"`{item['file']}`" if item.get("file") and item["file"] not in ("unknown", "N/A") else ""
        line_ref = f" line {item['line']}" if item.get("line") and item["line"] != "N/A" else ""
        loc = f" — {file_ref}{line_ref}" if file_ref or line_ref else ""
        lines.append(
            f"**{emoji} {sev.upper()}**{loc}  \n"
            f"{item.get('description', '')}  \n"
            f"> 💡 {item.get('suggestion', '')}\n"
        )
    return "\n".join(lines)

def format_review_comment(review: dict) -> str:
    score = review.get("overall_score", "N/A")
    summary = review.get("summary", "")
    positives = review.get("positive", [])

    body = f"## 🧠 MergeMind Review\n\n**Score: {score}/10**\n\n{summary}\n"
    body += _format_findings(review.get("bugs", []), "🐛 Bugs")
    body += _format_findings(review.get("security", []), "🔒 Security")
    body += _format_findings(review.get("style", []), "✨ Style & Best Practices")

    if positives:
        body += "\n### ✅ What's Good\n"
        for item in positives:
            body += f"- {item}\n"

    body += "\n---\n*Generated by [MergeMind](https://github.com/Ashu07017/mergemind) · Powered by Groq + Llama 3.3*"
    return body

def post_review_comment(repo: str, pr_number: int, review: dict):
    token = os.environ["GITHUB_TOKEN"]
    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    body = format_review_comment(review)

    response = requests.post(url, headers=headers, json={"body": body}, timeout=20)

    if response.status_code == 403:
        raise PermissionError("GitHub token lacks write access to pull requests. Check token scopes.")

    response.raise_for_status()
    comment_url = response.json().get("html_url")
    print(f"[MergeMind] Comment posted: {comment_url}")
    return comment_url